#!/usr/bin/env bash
# Собирает анимации в бандлы, которые выполняет JavaScriptCore внутри приложения:
#   Resources/pieces.json → Resources/pieces.js  — публичные (ascii.rest и pieces/*.ts);
#   local/pieces.json     → local/pieces.js      — приватные из local/ (папка в .gitignore), если она есть.
# Анимации ascii.rest (MIT, github.com/bas3line/ascii) — чистые функции frame(t) -> string, без DOM и зависимостей.
set -euo pipefail

REPO=https://github.com/bas3line/ascii.git
COMMIT=813ea2a233b56cc1c67a00d1e65ded21845ed1cd
ESBUILD=esbuild@0.28.2

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

git clone --quiet --filter=blob:none --no-checkout "$REPO" "$WORK/ascii"
git -C "$WORK/ascii" checkout --quiet "$COMMIT"
# Свои анимации написаны по тому же контракту: кладём их в дерево ascii.rest, чтобы import "../types.ts" разрешился.
cp "$ROOT"/pieces/*.ts "$WORK/ascii/src/pieces/"
if [ -d "$ROOT/local/pieces" ]; then cp "$ROOT"/local/pieces/*.ts "$WORK/ascii/src/pieces/"; fi

# bundle <список.json> <бандл.js>: анимации из списка — в IIFE, который дописывает их в globalThis.ASCII_PIECES.
bundle() {
  local ids
  ids="$(node -e 'console.log(require(process.argv[1]).map((p) => p.id).join(" "))' "$1")"
  {
    echo "// generated by fetch-pieces.sh"
    for p in $ids; do echo "import * as p_${p//-/_} from \"./ascii/src/pieces/$p.ts\";"; done
    echo "Object.assign(((globalThis as any).ASCII_PIECES ??= {}), {"
    for p in $ids; do echo "  \"$p\": p_${p//-/_},"; done
    echo "});"
  } > "$WORK/entry.ts"
  # Из $WORK, чтобы в комментариях бандла были относительные пути, а не временная папка.
  (cd "$WORK" && npx --yes "$ESBUILD" entry.ts --bundle --format=iife --target=es2020 --legal-comments=none \
    --banner:js="/* AsciiPet pieces. ascii.rest animations by @bas3line, MIT License, commit ${COMMIT:0:7}. See THIRD_PARTY_NOTICES.md */" \
    --outfile="$2" --log-level=warning)
  echo "OK: $2 ($(wc -c < "$2" | tr -d ' ') bytes): $ids"
}

bundle "$ROOT/Resources/pieces.json" "$ROOT/Resources/pieces.js"
cp "$WORK/ascii/LICENSE" "$ROOT/Resources/ascii.rest-LICENSE.txt"
if [ -f "$ROOT/local/pieces.json" ]; then bundle "$ROOT/local/pieces.json" "$ROOT/local/pieces.js"; fi
